version: "3.9"
services:
    rabbitmq:
        # https://hub.docker.com/_/rabbitmq
        image: rabbitmq:3.9.7-management-alpine
        container_name: rabbitmq
        ports:
            - 5672:5672 # AMQP
            - 15672:15672 # HTTP (Management)
